# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/erwincoumans/develop/tinyrenderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/erwincoumans/develop/tinyrenderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erwincoumans/develop/tinyrenderer/CMakeFiles /Users/erwincoumans/develop/tinyrenderer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/erwincoumans/develop/tinyrenderer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello_tinyrenderer

# Build rule for target.
hello_tinyrenderer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_tinyrenderer
.PHONY : hello_tinyrenderer

# fast build rule for target.
hello_tinyrenderer/fast:
	$(MAKE) -f CMakeFiles/hello_tinyrenderer.dir/build.make CMakeFiles/hello_tinyrenderer.dir/build
.PHONY : hello_tinyrenderer/fast

#=============================================================================
# Target rules for targets named tinyrenderer

# Build rule for target.
tinyrenderer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyrenderer
.PHONY : tinyrenderer

# fast build rule for target.
tinyrenderer/fast:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/build
.PHONY : tinyrenderer/fast

#=============================================================================
# Target rules for targets named pytinyrenderer

# Build rule for target.
pytinyrenderer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pytinyrenderer
.PHONY : pytinyrenderer

# fast build rule for target.
pytinyrenderer/fast:
	$(MAKE) -f python/CMakeFiles/pytinyrenderer.dir/build.make python/CMakeFiles/pytinyrenderer.dir/build
.PHONY : pytinyrenderer/fast

examples/cpp/hello_tinyrenderer.o: examples/cpp/hello_tinyrenderer.cpp.o

.PHONY : examples/cpp/hello_tinyrenderer.o

# target to build an object file
examples/cpp/hello_tinyrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/hello_tinyrenderer.dir/build.make CMakeFiles/hello_tinyrenderer.dir/examples/cpp/hello_tinyrenderer.cpp.o
.PHONY : examples/cpp/hello_tinyrenderer.cpp.o

examples/cpp/hello_tinyrenderer.i: examples/cpp/hello_tinyrenderer.cpp.i

.PHONY : examples/cpp/hello_tinyrenderer.i

# target to preprocess a source file
examples/cpp/hello_tinyrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/hello_tinyrenderer.dir/build.make CMakeFiles/hello_tinyrenderer.dir/examples/cpp/hello_tinyrenderer.cpp.i
.PHONY : examples/cpp/hello_tinyrenderer.cpp.i

examples/cpp/hello_tinyrenderer.s: examples/cpp/hello_tinyrenderer.cpp.s

.PHONY : examples/cpp/hello_tinyrenderer.s

# target to generate assembly for a file
examples/cpp/hello_tinyrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/hello_tinyrenderer.dir/build.make CMakeFiles/hello_tinyrenderer.dir/examples/cpp/hello_tinyrenderer.cpp.s
.PHONY : examples/cpp/hello_tinyrenderer.cpp.s

geometry.o: geometry.cpp.o

.PHONY : geometry.o

# target to build an object file
geometry.cpp.o:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/geometry.cpp.o
.PHONY : geometry.cpp.o

geometry.i: geometry.cpp.i

.PHONY : geometry.i

# target to preprocess a source file
geometry.cpp.i:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/geometry.cpp.i
.PHONY : geometry.cpp.i

geometry.s: geometry.cpp.s

.PHONY : geometry.s

# target to generate assembly for a file
geometry.cpp.s:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/geometry.cpp.s
.PHONY : geometry.cpp.s

model.o: model.cpp.o

.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i

.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s

.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/model.cpp.s
.PHONY : model.cpp.s

our_gl.o: our_gl.cpp.o

.PHONY : our_gl.o

# target to build an object file
our_gl.cpp.o:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/our_gl.cpp.o
.PHONY : our_gl.cpp.o

our_gl.i: our_gl.cpp.i

.PHONY : our_gl.i

# target to preprocess a source file
our_gl.cpp.i:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/our_gl.cpp.i
.PHONY : our_gl.cpp.i

our_gl.s: our_gl.cpp.s

.PHONY : our_gl.s

# target to generate assembly for a file
our_gl.cpp.s:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/our_gl.cpp.s
.PHONY : our_gl.cpp.s

tgaimage.o: tgaimage.cpp.o

.PHONY : tgaimage.o

# target to build an object file
tgaimage.cpp.o:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/tgaimage.cpp.o
.PHONY : tgaimage.cpp.o

tgaimage.i: tgaimage.cpp.i

.PHONY : tgaimage.i

# target to preprocess a source file
tgaimage.cpp.i:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/tgaimage.cpp.i
.PHONY : tgaimage.cpp.i

tgaimage.s: tgaimage.cpp.s

.PHONY : tgaimage.s

# target to generate assembly for a file
tgaimage.cpp.s:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/tgaimage.cpp.s
.PHONY : tgaimage.cpp.s

tinyrenderer.o: tinyrenderer.cpp.o

.PHONY : tinyrenderer.o

# target to build an object file
tinyrenderer.cpp.o:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/tinyrenderer.cpp.o
.PHONY : tinyrenderer.cpp.o

tinyrenderer.i: tinyrenderer.cpp.i

.PHONY : tinyrenderer.i

# target to preprocess a source file
tinyrenderer.cpp.i:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/tinyrenderer.cpp.i
.PHONY : tinyrenderer.cpp.i

tinyrenderer.s: tinyrenderer.cpp.s

.PHONY : tinyrenderer.s

# target to generate assembly for a file
tinyrenderer.cpp.s:
	$(MAKE) -f CMakeFiles/tinyrenderer.dir/build.make CMakeFiles/tinyrenderer.dir/tinyrenderer.cpp.s
.PHONY : tinyrenderer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello_tinyrenderer"
	@echo "... tinyrenderer"
	@echo "... pytinyrenderer"
	@echo "... examples/cpp/hello_tinyrenderer.o"
	@echo "... examples/cpp/hello_tinyrenderer.i"
	@echo "... examples/cpp/hello_tinyrenderer.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... our_gl.o"
	@echo "... our_gl.i"
	@echo "... our_gl.s"
	@echo "... tgaimage.o"
	@echo "... tgaimage.i"
	@echo "... tgaimage.s"
	@echo "... tinyrenderer.o"
	@echo "... tinyrenderer.i"
	@echo "... tinyrenderer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

